package com.ad.ast;

public enum AstNodeTypeEnum {
	PROGRAM,
	LET_STATEMENT,
	RETURN_STATEMENT,
	IDENTIFIER,
	INTEGER_LITERAL,
	EXPRESSION_STATEMENT,
	PREFIX_EXPRESSION,
	INFIX_EXPRESSION,
	BOOLEAN,
	IF_EXPRESSION,
	BLOCK_STATEMENT,
	FUNCTION_LITERAL,
	CALL_EXPRESSION,
	STRING_LITERAL,
	WHILE_EXPRESSION,
	ASSIGN_STATEMENT,
	DEF_STATEMENT,
	LIST_EXPRESSION
}
