#ifndef AD_BUILTINS_REGISTRY_NAMES_H
#define AD_BUILTINS_REGISTRY_NAMES_H

// Stable OP_GET_BUILTIN / symbol-table order (must match builtins_map keys in builtins.cpp).
static const char* const AD_VM_BUILTIN_NAMES[] = {
    "len",
    "exit",
    "print",
    "println",
    "ref_count",
    "type",
    "__keys",
    "__append",
    "__pop",
    "__remove",
    "__upper",
    "__lower",
    "__context",
    "__locals",
    "__iofile",
    "__syssystem",
    "__iosocket",
    "__memory_address",
    "eval",
    "__first",
    "__last",
    "map",
    "input",
    "list",
    "mat",
    "hash",
    "hasattr",
    "getattr",
    "setattr",
    "getattrs",
    "__thread",
    "import",
    "sleep",
    "delay",
    "join",
    "task_status",
    "task_cancel",
    "task_metrics",
    "str",
    "repr",
    "assert",
    nullptr,
};

#endif
