class ObjectType(object):
    NULL = "NULL"
    INTEGER = "INTEGER"
    BOOLEAN = "BOOLEAN"
    STRING = "STRING"
    RETURN_VALUE = "RETURN_VALUE"
    FUNCTION = "FUNCTION"
    STRING = "STRING"
    ERROR = "ERROR"